### ISSUE TITLE
[QEMU-1] Реализовать Dockerfile для u-boot под qemu-riscv64 в podman

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#1]
Собрать по инструкции (по [ссылке](https://github.com/u-boot/u-boot/blob/master/doc/board/emulation/qemu-riscv.rst)) u-boot под qemu-riscv64, используя контейнеризацию на основе podman.

**Definition of done:**
Добавлен Dockerfile для сборки и запуска U-boot в QEMU.

**Comment by CorvusSharp** [comment]
[Реализован Dockerfile для u-boot под qemu-riscv64 в podman](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/4)

**Comment by oorschnai** [comment]
Dockerfile принят. Ожидается описание на wiki и демонстрация работы

**Comment by oorschnai** [comment]
Хорошо
