### ISSUE TITLE
Изучить QEMU

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#10]
Изучить QEMU для выполнения задач на следующей итерации.

**Comment by dmitrij-zavrazhin-1304** [comment]
С теоретической и практической сторон был изучен инструмент витуализации QEMU с акцентом на эмуляцию архитектуры RISC-V.

**Comment by CorvusSharp** [comment]
Была изучена система виртуализации [Qemu с архитектурой RISC-V](https://www.qemu.org/docs/master/system/target-riscv.html)
