### ISSUE TITLE
[QEMU-3] Реализовать Dockerfile для сборки ядра linux

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#12]
Реализовать Dockerfile для сборки ядра linux под qemu-riscv64, используя контейнеризацию на основе podman.
Причина возникновения задачи: ядро, которое собирается при помощи YOCTO, не поддерживает сборку и запуск на QEMU.

**Definition of done:**
Добавлен Dockerfile для сборки и запуска ядра linux в QEMU.

**Comment by pddemchuk** [comment]
Сделан [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/6)

**Comment by oorschnai** [comment]
Принято и смержено. Ожидается описание на wiki

**Comment by oorschnai** [comment]
Хорошо.
