### ISSUE TITLE
[YOCTO-3] Добавить конфигурацию NAT в YOCTO

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#14]
Добавить конфигурацию NAT в YOCTO по инструкции по [ссылке](https://hub.mender.io/t/adding-docker-and-docker-compose-to-a-yocto-build/6078)

**Definition of done:**
При сборке образа добавляется конфигурация NAT.

**Comment by sashachernyakova** [comment]
открыт #[PR](https://github.com/moevm/mse1h2024-xuantie-yocto/pull/2)

**Comment by oorschnai** [comment]
Хорошо.
