### ISSUE TITLE
[QEMU-4] Добавить логирование запускаемых виртуальных машин

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#15]
Добавить способ логирования запускаемых виртуальных машин.

**Definition of done:**
При запуске виртуальной машины все выводимое на ее консоль отражается в логах.

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/13)

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/14)

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/16)

**Comment by oorschnai** [comment]
Все PR приняты

**Comment by oorschnai** [comment]
Хорошо.
