### ISSUE TITLE
[DOC-1] Описать на wiki изменения, связанные с QEMU

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#17]
Создать страницу на вики и описать какая работа, связанная с qemu, была проделана в течение второй итерации. 

**Definition of done:**
На вики создана страница, содержащая описание внесенных изменений. Упомянуты итоги всех выполненных задач с меткой [QEMU-*] в названии.

**Comment by sashachernyakova** [comment]
сделано
