### ISSUE TITLE
[QEMU-2] Реализовать Dockerfile для QEMU в podman

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#2]
Собрать по инструкции (по [ссылке](https://github.com/T-head-Semi/qemu)) QEMU для виртуализации процессоров, используя контейнеризацию на основе podman.

**Definition of done:**
Создан Dockerfile для сборки и запуска QEMU в контейнере.

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/5)

**Comment by oorschnai** [comment]
Dockerfile принят. Ожидается описание на wiki и демонстрация работы

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/7)

**Comment by oorschnai** [comment]
PR смержен

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/8)

**Comment by oorschnai** [comment]
PR принят

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/9)

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/11)

**Comment by oorschnai** [comment]
Хорошо. Принято

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/17)

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/19)

**Comment by oorschnai** [comment]
Приняты

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/22)

**Comment by oorschnai** [comment]
Хорошо
