### ISSUE TITLE
[CI-3] Добавить параметризацию в linux.Dockerfile

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#22]
Добавить параметризацию сборки контейнера в linux.Dockerfile. Параметризации подлежат: пути подключения томов, ветки репозиториев, количество потоков сборки и имя конфигурационного файла для сборки ядра.

**Definition of done:**
В linux.Dockerfile добавлены все перечисленные параметры.

**Comment by pddemchuk** [comment]
[PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/49)
