### ISSUE TITLE
[CI-4] Добавить параметризацию в qemu.Dockerfile

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#23]
Добавить параметризацию сборки контейнера в qemu.Dockerfile. Параметризации подлежат: пути подключения томов и количество потоков сборки.

**Definition of done:**
В qemu.Dockerfile добавлены все перечисленные параметры.

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыл [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/35)

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыл [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/35)

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыл [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/40)

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/41)
