### ISSUE TITLE
[CI-5] Добавить параметризацию в uboot.Dockerfile

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#24]
Добавить параметризацию сборки контейнера в uboot.Dockerfile. Параметризации подлежат: пути подключения томов, ветки репозиториев, количество потоков сборки, платформа для OpenSBI и имя конфигурационного файла для сборки uboot.

**Definition of done:**
В uboot.Dockerfile добавлены все перечисленные параметры.

**Comment by CorvusSharp** [comment]
[открыт pull request](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/39)
