### ISSUE TITLE
[CI-6] Добавить параметризацию в Makefile

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#25]
Добавить параметризацию системы сборки в Makefile с возможностью передавать переменные извне. 

**Definition of done:**
Makefile обеспечивает передачу всех поддерживаемых параметров в Dockerfiles.

**Comment by pddemchuk** [comment]
[PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/65)
