### ISSUE TITLE
[CI-7] Добавить скрипты, реализующие базовые интеграционные тесты

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#26]
Добавить скрипты, реализующие базовое тестирование запуска всех компонентов вместе.

**Definition of done:**
В репозиторий добавлены соответствующие скрипты.

**Comment by dmitrij-zavrazhin-1304** [comment]
PR's added: [1](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/54), [2](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/55).
