### ISSUE TITLE
[CI-8] Добавить скрипт, реализующий базовое функциональное тестирование ssh

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#27]
Добавить скрипт, реализующий базовое функциональное тестирование подключения через ssh.

**Definition of done:**
В репозиторий добавлен соответствующий скрипт.

**Comment by CorvusSharp** [comment]
[Открыт PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/52)
