### ISSUE TITLE
[QEMU-5] Реализовать приведение репозитория в корректное состояние в linux.Dockerfile

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#33]
Реализовать приведение репозитория в корректное состояние в linux.Dockerfile. 
1. Добавить проверку на пустоту директории
2. Добавить else, приводящий уже склонированный репозиторий в корректное состояние

**Definition of done:**
В linux.Dockerfile внесены соответствующие изменения.

**Comment by pddemchuk** [comment]
[PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/45)
