### ISSUE TITLE
[QEMU-6] Реализовать приведение репозитория в корректное состояние в qemu.Dockerfile

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#34]
Реализовать приведение репозитория в корректное состояние в qemu.Dockerfile. 
1. Добавить проверку на пустоту директории
2. Добавить else, приводящий уже склонированный репозиторий в корректное состояние

**Definition of done:**
В qemu.Dockerfile внесены соответствующие изменения.

**Comment by CorvusSharp** [comment]
открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/44)
