### ISSUE TITLE
[QEMU-7] Реализовать приведение репозитория в корректное состояние в uboot.Dockerfile

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#35]
Реализовать приведение репозитория в корректное состояние в uboot.Dockerfile. 
1. Добавить проверку на пустоту директории
2. Добавить else, приводящий уже склонированный репозиторий в корректное состояние

**Definition of done:**
В uboot.Dockerfile внесены соответствующие изменения.

**Comment by sashachernyakova** [comment]
В uboot.Dockerfile внесены соответствующие изменения.
#[PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/50)
