### ISSUE TITLE
[QEMU-8] Декомпозировать linux.Dockerfile и uboot.Dockerfile 

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#36]
Декомпозировать linux.Dockerfile и uboot.Dockerfile с вынесением сборки тулчейна в отдельный образ

**Definition of done:**
Создан riscv-gnu-toolchain.Dockerfile

**Comment by dmitrij-zavrazhin-1304** [comment]
A wild [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/53) appears!
