### ISSUE TITLE
[QEMU-9] Декомпозировать qemu.Dockerfile

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#37]
Декомпозировать qemu.Dockerfile с вынесением сборки qemu в отдельный образ

**Definition of done:**
Создан qemu-builder.Dockerfile

**Comment by CorvusSharp** [comment]
[Создан qemu-builder.Dockerfile](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/46)
