### ISSUE TITLE
[REPO-2] Удалить неиспользуемые подмодули в репозитории

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#40]
Удалить неиспользуемые подмодули, унаследованные от sipeed/LicheePi4A.

**Definition of done:**
Оставлены только используемые подмодули.

**Comment by CorvusSharp** [comment]
[выолнен PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/72)
[выолнен PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/73)
