### ISSUE TITLE
[REPO-5] Описание ожидаемого результата в README 

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#48]
Добавить в readme описание как после запуска тестов убедиться, что все ок

**Definition of done:**
В readme есть описание как после запуска тестов понять, что все ок

**Comment by dmitrij-zavrazhin-1304** [comment]
Добавлен [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/60)

**Comment by dmitrij-zavrazhin-1304** [comment]
Добавлен [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/61)

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/62)

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/63)

**Comment by dmitrij-zavrazhin-1304** [comment]
Открыт [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/64)

**Comment by dmitrij-zavrazhin-1304** [comment]
[PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/68) opened
