### ISSUE TITLE
[CI-1] Автоматизация сборки rootfs

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#5]
Модифицировать Dockerfile.yocto так, чтобы сборка rootfs осуществлялась автоматически.

**Definition of done:**
В Dockerfile.yocto внесены необходимые изменения.

**Comment by pddemchuk** [comment]
Сделан [PR](https://github.com/moevm/mse1h2024-licheepi4a-sdk/pull/18)

**Comment by oorschnai** [comment]
Принят

**Comment by oorschnai** [comment]
Хорошо.
