### ISSUE TITLE
Создать сценарии использования

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#7]
Создать сценарии использования для двух случаев: 1) когда у пользователя есть готовый образ и 2) когда у пользователя нет готового образа. Разместить результат на wiki проекта.

**Definition of done:**
На wiki размещены сценарии использования.

**Comment by CorvusSharp** [comment]
Был создан сценарий использования, результат размещен на [wiki](https://github.com/moevm/mse1h2024-licheepi/wiki/%D0%9F%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B8,-%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F,-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B8-%D0%BC%D0%B0%D0%BA%D0%B5%D1%82-UI)
