### ISSUE TITLE
Изучить YOCTO

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#8]
Изучить Yocto для выполнения задач на следующей итерации.

**Comment by pddemchuk** [comment]
были изучены возможности yocto

**Comment by sashachernyakova** [comment]
Изучены возможности йокто, которые будут необходимы на следующих итерациях

**Comment by GeorIsay** [comment]
Ознокмился с необходимыми для работы с проектом аспектами Yocto

**Comment by oorschnai** [comment]
Принято
