### ISSUE TITLE
Изучить docker и podman

### ISSUE THREAD

**Issue by oorschnai** [moevm/mse1h2024-licheepi#9]
Изучить docker и/или podman для выполнения задач на следующей итерации.

**Comment by dmitrij-zavrazhin-1304** [comment]
С теоретической и практической сторон были изучены инструменты работы с контейнерами docker и podman.

**Comment by pddemchuk** [comment]
были изучены основы контейнеризации

**Comment by CorvusSharp** [comment]
Были изучены инструменты [dokcera](https://www.youtube.com/watch?v=O8N1lvkIjig&t=11064s)

**Comment by sashachernyakova** [comment]
Были изучены теоретические материалы по докеру, необходимые для выполнения задач на следующей итерации

**Comment by GeorIsay** [comment]
Изучил необходимые для проекта аспекты инструментов docker и podman

**Comment by oorschnai** [comment]
Принято
